### ISSUE TITLE
v1.0.2 is stripping comments from values.yaml

### ISSUE THREAD

**Issue by derlin** [belitre/helm-push-artifactory-plugin#75]
Hi there ! First, thank you for this very useful plugin.

The latest release v1.0.2 added (fixed) the possibility to override values upon push. 
The problem is that by rewriting `values.yaml`, all comments and new lines are stripped from the file. 
This is very problematic as it goes against [Helm good practices](https://helm.sh/docs/chart_best_practices/values/#document-valuesyaml).

Example of values.yaml pushed using 1.0.1:
```yaml
# @Copyright YYY
# This file defines the default values used by the XX-library.
# To reference them in your own Chart templates, use `.Values.XXX`.
# To override any of them in your own values.xml, do not forget the "XX" key.

# name of the project, this is required
project: null
# some other property, blabla documentation
other: 12
```

The same values.yaml pushed to artifactory using 1.0.2:
```yaml
project:null
other: 12
```

I understand keeping comments makes the override of values difficult.
However, I would expect that if I don't use the override feature (not `-s` options passed), the values.yaml should be pushed unchanged.
